database_url = "host=localhost user=botkai password=password dbname=botdb sslmode=disable options='--client_encoding=UTF8'"
bind_addr = ":8282"
chetnost = 0
firebase_project_id="capypara-project"
firebase_service_account_key_path = "configs/serviceAccountKey.json"
influxdb_name = "capypara"
influxdb_url = "influx_url"
influxdb_token = "token=="
