database_url = "host=localhost user=botkai password=password dbname=botdb sslmode=disable options='--client_encoding=UTF8'"
bind_addr = ":8282"
chetnost = 0
firebase_project_id="capypara-1"
firebase_service_account_key_path = "configs/serviceAccountKey.json"
influxdb_name = "capypara"
influxdb_url = "https://url"
influxdb_token = "token=="
yookassa_shop_id = 123456
yookassa_api_key = "test_123_token"
